name: pr01_m08_uf2_linaresjoan
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^6.1.4
  provider: ^6.1.5
  intl: ^0.20.2
  http: ^1.3.0
  diacritic: ^0.1.6
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true

flutter_icons:
  image_path: "assets/icon/app_icon.png"
  android: true
  ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon.png"